services:
  scraper:
    container_name: scraper_tucambista
    build:
      context: .
    command: sh -c "while true; do python3 main.py; sleep 60; done"  # Ejecuta main.py cada 60 segundos
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./scraper:/app/scraper
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped

  web:
    container_name: web_tucambista
    build:
      context: .
    command: streamlit run app.py --server.port=8501 --server.address=0.0.0.0
    ports:
      - "8502:8501"
    volumes:
      - .:/app
    depends_on:
      - scraper
    restart: unless-stopped
